/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.PacienteHasMedico;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import DAO.PacienteHasMedicoDAO;
import control.ManipuladorPacientes;
import javax.swing.DefaultListModel;
import model.Paciente;

/**
 *
 * @author joaop
 */
public class MedicoListar extends javax.swing.JFrame {

    private ArrayList<PacienteHasMedico> listaPacientesH;
    public MedicoListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textListarPeloCRM = new javax.swing.JTextField();
        btMedicoListar = new javax.swing.JButton();
        btMedicoListarLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listLista = new javax.swing.JList<>();
        btListaLimpar = new javax.swing.JButton();
        btListaVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar médico"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar pelo CRM"));

        jLabel1.setText("CRM");

        textListarPeloCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textListarPeloCRMActionPerformed(evt);
            }
        });

        btMedicoListar.setText("Listar");
        btMedicoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicoListarActionPerformed(evt);
            }
        });

        btMedicoListarLimpar.setText("Limpar");
        btMedicoListarLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicoListarLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(textListarPeloCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMedicoListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMedicoListarLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textListarPeloCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btMedicoListar)
                    .addComponent(btMedicoListarLimpar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacientes com consulta marcada"));

        jScrollPane2.setViewportView(listLista);

        btListaLimpar.setText("Limpar");
        btListaLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaLimparActionPerformed(evt);
            }
        });

        btListaVoltar.setText("Voltar");
        btListaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btListaVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btListaLimpar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListaLimpar)
                    .addComponent(btListaVoltar)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textListarPeloCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textListarPeloCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textListarPeloCRMActionPerformed

    private void btMedicoListarLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicoListarLimparActionPerformed
        textListarPeloCRM.setText("");
        DefaultListModel model=new DefaultListModel();
        model.clear();
        listLista.setModel(model);
    }//GEN-LAST:event_btMedicoListarLimparActionPerformed

    private void btMedicoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicoListarActionPerformed
        PacienteHasMedico paciente;
        
        String crm = textListarPeloCRM.getText();
        PacienteHasMedicoDAO pacienteDao = new PacienteHasMedicoDAO();
        
        if (crm.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Digite um crm.",
                    "Busca", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            listaPacientesH = pacienteDao.buscarPacienteHasMedico();

            if (listaPacientesH!= null ) {
                mostraDados(Integer.parseInt(crm));          
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não encontrado!",
                        "Busca", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btMedicoListarActionPerformed

    private void btListaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaVoltarActionPerformed
        textListarPeloCRM.setText("");
        DefaultListModel model=new DefaultListModel();
        model.clear();
        listLista.setModel(model);
        this.setVisible(false);
    }//GEN-LAST:event_btListaVoltarActionPerformed

    private void btListaLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaLimparActionPerformed
        listLista.removeAll();
        DefaultListModel model=new DefaultListModel();
        model.clear();
        listLista.setModel(model);
    }//GEN-LAST:event_btListaLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoListar().setVisible(true);
            }
        });
    }
    private void mostraDados(int crm) {
        DefaultListModel DLM = new DefaultListModel<>();
        Paciente paciente;
        ManipuladorPacientes manipPacientes = new ManipuladorPacientes();

        for(PacienteHasMedico pacienteNaLista : listaPacientesH){
            if(pacienteNaLista.getCrm()== crm){
                paciente = manipPacientes.buscaPorCpf(pacienteNaLista.getCpf());
                DLM.addElement("Paciente: " + paciente.getNome());
                
            }
                
        }
       
        listLista.setModel(DLM);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListaLimpar;
    private javax.swing.JButton btListaVoltar;
    private javax.swing.JButton btMedicoListar;
    private javax.swing.JButton btMedicoListarLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listLista;
    private javax.swing.JTextField textListarPeloCRM;
    // End of variables declaration//GEN-END:variables
}
