/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import exception.ErroCadastroException;
import exception.ValorInvalidoException;
import javax.swing.JOptionPane;
import model.Paciente;
import control.ManipuladorPacientes;
import control.ManipuladorTelefones;
import model.Telefone;
public class PacienteAdicionar extends javax.swing.JFrame {

    
    public PacienteAdicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btTelaPacienteAdicionar = new javax.swing.JButton();
        btPacienteAdicionarVoltar = new javax.swing.JButton();
        textPacienteAdicionarNascimento = new javax.swing.JTextField();
        textPacienteAdicionarNome = new javax.swing.JTextField();
        textPacienteAdicionarTelefone = new javax.swing.JTextField();
        textPacienteAdicionarEndereco = new javax.swing.JTextField();
        textPacienteAdicionarCPF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar paciente"));

        jLabel6.setText("Telefone");

        jLabel5.setText("Endereço");

        jLabel4.setText("CPF");

        jLabel3.setText("Data de nascimento");

        jLabel2.setText("Nome");

        btTelaPacienteAdicionar.setText("Adicionar");
        btTelaPacienteAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaPacienteAdicionarActionPerformed(evt);
            }
        });

        btPacienteAdicionarVoltar.setText("Voltar");
        btPacienteAdicionarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacienteAdicionarVoltarActionPerformed(evt);
            }
        });

        textPacienteAdicionarNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteAdicionarNascimentoActionPerformed(evt);
            }
        });

        textPacienteAdicionarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteAdicionarNomeActionPerformed(evt);
            }
        });

        textPacienteAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteAdicionarTelefoneActionPerformed(evt);
            }
        });

        textPacienteAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteAdicionarEnderecoActionPerformed(evt);
            }
        });

        textPacienteAdicionarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacienteAdicionarCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btPacienteAdicionarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTelaPacienteAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textPacienteAdicionarNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPacienteAdicionarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPacienteAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPacienteAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPacienteAdicionarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPacienteAdicionarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPacienteAdicionarNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPacienteAdicionarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPacienteAdicionarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPacienteAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btPacienteAdicionarVoltar)
                        .addComponent(btTelaPacienteAdicionar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPacienteAdicionarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteAdicionarCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteAdicionarCPFActionPerformed

    private void textPacienteAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteAdicionarEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteAdicionarEnderecoActionPerformed

    private void textPacienteAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteAdicionarTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteAdicionarTelefoneActionPerformed

    private void textPacienteAdicionarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteAdicionarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteAdicionarNomeActionPerformed

    private void textPacienteAdicionarNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacienteAdicionarNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacienteAdicionarNascimentoActionPerformed

    private void btTelaPacienteAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaPacienteAdicionarActionPerformed
        
        if (passouNaPreValidacaoPaciente()) {
            try {
                cadastraPaciente();
                verificaCadastrarNovamente();    
                    } catch (ValorInvalidoException | ErroCadastroException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                                "Erro", JOptionPane.ERROR_MESSAGE);
                        limpaCampos();
                    }
        }
        else{
            verificaCadastrarNovamente();
        }
       
        
    }//GEN-LAST:event_btTelaPacienteAdicionarActionPerformed

    private void btPacienteAdicionarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacienteAdicionarVoltarActionPerformed
        this.setVisible(false);       
        limpaCampos();
    }//GEN-LAST:event_btPacienteAdicionarVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteAdicionar().setVisible(true);
            }
        });
    }
    
    
    private void cadastraPaciente() throws ValorInvalidoException, ErroCadastroException {
        String nome = textPacienteAdicionarNome.getText();
        String nTelefone = textPacienteAdicionarTelefone.getText();
        String nascimento = textPacienteAdicionarNascimento.getText();
        String cpf = textPacienteAdicionarCPF.getText();
        String endereco = textPacienteAdicionarEndereco.getText();
        Paciente paciente = new Paciente();
        Telefone telefone = new Telefone();
        
        paciente.setNome(nome);
        paciente.setTelefone(Integer.parseInt(nTelefone));
        paciente.setNascimento(nascimento);
        paciente.setCpf(Integer.parseInt(cpf));
        paciente.setEndereco(endereco);

        telefone.setTelefone(Integer.parseInt(nTelefone));
        telefone.setNome(nome);
        
       
        new ManipuladorPacientes().cadastra(paciente,telefone);
    }
    
    private void limpaCampos() {
        textPacienteAdicionarNome.setText("");
        textPacienteAdicionarTelefone.setText("");
        textPacienteAdicionarNascimento.setText("");
        textPacienteAdicionarCPF.setText("");
        textPacienteAdicionarEndereco.setText("");
    }
    
    private void verificaCadastrarNovamente() {
        
        int respUsuario = JOptionPane.showConfirmDialog(rootPane,
                "Deseja cadastrar outro "
                + "paciente?", "Mensagem", JOptionPane.YES_NO_OPTION);
        
        switch (respUsuario) {
            
            case JOptionPane.YES_OPTION:
                limpaCampos();
                break;
            case JOptionPane.NO_OPTION:
                btPacienteAdicionarVoltar.doClick();
                limpaCampos();
                break;
            default:
                break;
        }
    }

    private boolean passouNaPreValidacaoPaciente() {
        String nome = textPacienteAdicionarNome.getText();
        String telefone = textPacienteAdicionarTelefone.getText();
        String nascimento = textPacienteAdicionarNascimento.getText();
        String cpf = textPacienteAdicionarCPF.getText();
        String endereco = textPacienteAdicionarEndereco.getText();

        if (nome.isEmpty() || telefone.isEmpty() || nascimento.isEmpty()|| cpf.isEmpty() || endereco.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem todos os campos foram "
                    + "preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPacienteAdicionarVoltar;
    private javax.swing.JButton btTelaPacienteAdicionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textPacienteAdicionarCPF;
    private javax.swing.JTextField textPacienteAdicionarEndereco;
    private javax.swing.JTextField textPacienteAdicionarNascimento;
    private javax.swing.JTextField textPacienteAdicionarNome;
    private javax.swing.JTextField textPacienteAdicionarTelefone;
    // End of variables declaration//GEN-END:variables
}
